services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mokse-web
    restart: unless-stopped
    ports:
      - "${APP_PORT:-3000}:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      # Add your new Notion API variables here
      - NOTION_API_KEY=${NOTION_TOKEN}
      - NOTION_DATABASE_ID=${NOTION_DATABASE_KEY}
    # Optional: If you want to keep a dev profile for hot-reloading
    profiles:
      - prod"